### ISSUE TITLE
Cannot render "null" json response

### ISSUE THREAD

**Issue by KimBurgess** [spider-gazelle/action-controller#15]
When attempting
```crystal
render json: nil
```
This is not correctly handled due the [default nil param (and checks against this)](https://github.com/spider-gazelle/action-controller/blob/e36c94357fe98b4edb5a20151878df5fa33ca222/src/action-controller/responders.cr#L87).

**Comment by stakach** [comment]
That's a challenging one. Simple to work around, not sure how simple it will be to resolve..
