### ISSUE TITLE
Use SO_REUSEPORT

### ISSUE THREAD

**Issue by waghanza** [spider-gazelle/action-controller#2]
Hi,

When initializing an `http/server` an option **COULD** be set to reuse the port.

@see https://github.com/crystal-lang/crystal/blob/7fb783f7afec0a199d6f22ef78aae0f45517068a/src/http/server.cr#L136

@stakach What do you think about it ?

Regards,

**Comment by stakach** [comment]
Thanks for pointing that out!
Definitely worthwhile setting this.
