### ISSUE TITLE
{{FILTER_TYPES}}_action working only with curl (specs) but not context (specs)

### ISSUE THREAD

**Issue by dukeraphaelng** [spider-gazelle/action-controller#25]
`before_action` works fine but if params `only` is added, it stops working.

This issue originally was discovered during the development of portal-auth-framework.

Specifically the code that was used were https://github.com/place-technology/portal-authentication/blob/master/src/controllers/mappings.cr and https://github.com/place-technology/portal-authentication/blob/master/src/controllers/users.cr

**Comment by stakach** [comment]
We use `only` all the time, there must be something else at play here

**Comment by dukeraphaelng** [comment]
I have found the devil.

I forgot to mention that it's not only `only` that wasn't work, it turns out that `before_action` was not working.

This is only the case if we use context instead of curl

For example, this runs fine with before_action in the controller:

https://github.com/spider-gazelle/action-controller/blob/414477bb14fad3595aac7ce9f9c318323cb6f69d/spec/response_spec.cr#L93-L97

However, the same specs, but use context instead of curl, fails

```crystal
    it "should perform before actions and execute the action" do
      result = context(method: "GET", route: "/hello/") { |i| HelloWorld.new(i).index }
      result.status_code.should eq 200
      result.output.to_s.should eq("set_var 123")
    end
```

The error log is as follows
```bash
  1) end to end requests and responses should perform before actions and execute the action
     Failure/Error: result.output.to_s.should eq("set_var 123")

       Expected: "set_var 123"
            got: "set_var "

     # spec/response_spec.cr:102

```

we can see clearly that it doesn't have `123`, only `set_var` this means the before_action block did not run.

**Comment by caspiano** [comment]
Ensuring that we can test callbacks with `context` based specs will make it _much_ easier to spec things

**Comment by caspiano** [comment]
Closed by the release of version 5. Callbacks _will_ be called in specs.
