### ISSUE TITLE
Crystal 0.36.0 released

### ISSUE THREAD

**Issue by Nicolab** [spider-gazelle/action-controller#33]
Hello,

First thanks for this awesome shard! It make the life easier and more comfortable.

Just to inform that the [latest Crystal version](https://crystal-lang.org/2021/01/26/crystal-0.36.0-released.html) has just been released and brings some breaking changes. Like `HTTP::Params` that becomes `URI::Params`.

Here the list: https://github.com/crystal-lang/crystal/releases/tag/0.36.0

**Comment by stakach** [comment]
Thanks for letting us know, we'll have an update out sometime in the next week

**Comment by Nicolab** [comment]
Nice :+1: 
Thanks
