### ISSUE TITLE
FileHandler after CompressHandler hangs response when requesting gzip

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/action-controller#5]
Sorry for the somewhat light on info bug report, hopefully you have enough to go off; I'm seeing an odd one using the default spider-gazelle template cloned down from github.

I've essentially only ran a shards install and then a `shards build && bin/app` in terms of application code, but to setup the rest of the state:

```
echo '() => {}' > www/index.js`
```
The 'copy as curl' output from my firefox request:
```
curl 'http://127.0.0.1:3000/index.js' -H 'User-Agent: Mozilla/5.0
 (Macintosh; Intel Mac OS X 10.14; rv:65.0) Gecko/20100101 Firefox/65.0' -H 'Accept: */*' -H 'Acce
pt-Language: en-GB,en;q=0.5' --compressed -H 'Referer: http://127.0.0.1:3000/' -H 'Connection: kee
p-alive' -H 'Cache-Control: max-age=0'
```

Placing the HTTP::CompressHandler after the ActionController::FileHandler prevents the request from hanging. 

After playing around with the above curl command, if you remove the `--compressed` flag it will work as expected.

**Comment by stakach** [comment]
Weird. it seems to serve compressed content fine for me. That's a built in library too so I am surprised there is an issue, but unfortunately it is probably unrelated to Spider-Gazelle.

Moving the `HTTP::CompressHandler` means the static file requests are not being compressed at all.
You are probably pretty safe to remove that handler all together or use nginx to apply the compression (depending on your deployment)

**Comment by jackturnbull** [comment]
> but unfortunately it is probably unrelated to Spider-Gazelle.

Yeah I agree with the assessment here having had a look at the code; you're really not adding loads and loads on top of the stdlib by the looks of things. Good point on external compression, thankfully I'll be fine to skip the compression here as it's going to sit behind Cloudflare.

Will close this one off because I don't think there's anything ontop of stdlib that could be causing this! Thanks again for the response :)
