### ISSUE TITLE
Habitat 0.4.1 incompatibility

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/action-controller#6]
Hello! Took a little while to diagnose but it appears that a habitat update currently causes an incompatibility when using the default spider-gazelle/spider-gazelle repo template:

```
Dependencies are satisfied
Building: app
Error target app failed to compile:
Error in macro 'create' /Users/jackturnbull/Documents/projects/spider-gazelle/lib/habitat/src/habitat.cr:128, line 33:

   1.     Habitat.track({{ @type }})
   2.
   3.     include Habitat::TempConfig
   4.     include Habitat::SettingsHelpers
   5.
   6.     HABITAT_SETTINGS = [] of Nil
   7.
   8.     def self.configure
   9.       yield settings
  10.     end
  11.
  12.     class Settings
  13.     end
  14.
  15.     def self.settings
  16.       Settings
  17.     end
  18.
  19.     def settings
  20.       Settings
  21.     end
  22.
  23.     begin setting(key : String)
  24. setting(secret : String)
  25. setting(max_age : Int32 = NEVER)
  26. setting(secure : Bool = false)
  27. setting(encrypted : Bool = true)
  28. setting(path : String = "/")
  29.  end
  30.
  31.     # inherit_habitat_settings_from_superclass
  32.
> 33.     macro finished
  34.       Habitat.create_settings_methods({{ @type }})
  35.     end
  36.

expanding macro
in macro 'finished' expanded macro: create:33, line 1:

>  1.       Habitat.create_settings_methods(ActionController::Session)
   2.

expanding macro
in lib/action-controller/src/action-controller.cr:31: undefined macro method 'NamedTupleLiteral#type'

        {% if decl.type.is_a?(Union) && decl.type.types.map(&.id).includes?(Nil.id) %}
```

It's an easy enough one to reproduce;
1. Pull down fresh spider-gazelle document template
2. shards install
3. shards build

I'd debated raising it over at Habitat too, although I thought I'd start here to begin.

Solved (for the time being) by pinning habitat to 0.4.0

**Comment by stakach** [comment]
Yeah, I've had an open pull request for awhile
luckyframework/habitat#34

Will take a look and update today

**Comment by jackturnbull** [comment]
Ah I didn't spot that, thanks! Worst case scenario I'll run off your branch for a bit

**Comment by stakach** [comment]
habitat `0.4.0` is fine, the Spider-Gazelle code is just monkey patching that pull request - I should have pinned the version on my side

**Comment by stakach** [comment]
Thanks for letting me know. This is resolved for now.
Feel free to give your support over at: luckyframework/habitat#34 too :)

**Comment by jackturnbull** [comment]
Brilliant, thanks for getting this sorted (again!)
