### ISSUE TITLE
to_json { renders string, not json }

### ISSUE THREAD

**Issue by didactic-drunk** [spider-gazelle/action-controller#61]
```crystal
def index
  respond_with do
      json do
        data = { "id" => 1 }
        ... conditional data assignments ...
        data
      end
  end
end
```

Expected:
```
{"id": 1}
```
Received:
```
{"id" => 1}
```

I could call `data.to_json`, but
1. `to_json(io)` streaming is unavailable
3. This violates the POLS
3. What is the use case for using `to_s` and not `to_json`?

**Comment by stakach** [comment]
fixed in 1cdbcdd1529cdf241a5491920aeff7ea55c05cdc
