### ISSUE TITLE
`add_parser` does not work if `content-type` includes `;charset=...`

### ISSUE THREAD

**Issue by np-nam** [spider-gazelle/action-controller#74]
It does not match if you only add `add_parser("text/plain")`, and it will cause macro expansion error if you try to add the trailing `;charset=...` string.

**Comment by stakach** [comment]
I think we should fix the not matching issue. I'll take a look today

**Comment by stakach** [comment]
@np-nam requests that specify the charset no longer fail.
Additionally, the default body parser takes into account the body charset when processing requests.
You can do something similar for any additional body content types you wish to support (converts the bodies data into crystals supported UTF-8 charset)

https://github.com/spider-gazelle/action-controller/blob/d4392487d2e308a9bf114b3bb1e71e12351da2f6/src/action-controller/router/builder.cr#L478-L482
