### ISSUE TITLE
__parse_inferred_routes__ macro does not remove some non-identifier characters 

### ISSUE THREAD

**Issue by n-pn** [spider-gazelle/action-controller#75]
annotations like `@[AC::Route::GET("/?:id")` or `@[AC::Route::GET("/!/:id")` will not work, they will generate invalid method names.

macros like `get`, `post` also generate broken method names similar to above.

some characters like `-`, `~` is properly removed though.

p/s: I replaced all occurrences of `.gsub(/|\-|\~|\*|\:|\./, "_")` with `.gsub(/\W/, "_")` in the macros and it works again.

**Comment by stakach** [comment]
thanks for the pointer!
Happy to patch and / or happy to accept a pull request

**Comment by n-pn** [comment]
@stakach it is a small change so I don't really want to take credit for it :)

**Comment by stakach** [comment]
new version v5.5.4 released, thanks
