### ISSUE TITLE
Inverted logic in file deletion

### ISSUE THREAD

**Issue by KasKatto** [spider-gazelle/action-controller#81]
Oversight on my part when writing the statement:
https://github.com/spider-gazelle/action-controller/blob/master/src/action-controller/base.cr#L145
Should be using "if" not "unless"
(P.S. Sorry its 2AM in the UK)

**Comment by stakach** [comment]
it seems correct to me. Delete the file if it hasn't been moved.

**Comment by KasKatto** [comment]
Issue is  #has_moved returns true if the file hasn't moved since the original path will be equal to the current path. Might also be a good idea to change the name of #has_moved to something like #hasnt_moved so that it matches with the expected value.

**Comment by stakach** [comment]
I still don't see it

```crystal
def has_moved? : Bool
  @original_path != @file.path
end

# delete if the original_path == file.path
file_upload.file.delete unless file_upload.has_moved?
```

**Comment by KasKatto** [comment]
Wait no. Im talking non-sense. Ignore that. Issue isn't inverted logic here. Actual issue is that #has_moved? always returns false no matter if the file has been moved or not. In my controller i use FileUtils#mv(uploaded_file.file.path, new_path) to move the file. It moves the file correctly, however @file.path never updates.

**Comment by stakach** [comment]
thanks! That I can fix
