### ISSUE TITLE
Unable to create route with "." (dot) in route name

### ISSUE THREAD

**Issue by jackturnbull** [spider-gazelle/action-controller#9]
Sorry I don't have a PR ready for this one, I haven't been able to dig too deeply - you might have more of an idea than me for a quick fix but I'll take a look if you're unable.

It seems like we can't create routes with a dot character in the route name. You can replicate it easily enough from the spider-gazelle default template:

```crystal
class Welcome < Application
  base "/"

  def index
    welcome_text = "You're being trampled by Spider-Gazelle!"

    respond_with do
      html template("welcome.ecr")
      text "Welcome, #{welcome_text}"
      json({welcome: welcome_text})
      xml do
        XML.build(indent: "  ") do |xml|
          xml.element("welcome") { xml.text welcome_text }
        end
      end
    end
  end

  get "index.html", :index_html do
    render text: "<html></html>"
  end
end
```

The use case might be apparent from the example, but this is to basically intercept calls to 'static assets' and template them as if they were server-side rendered.

This is the console error:
```
Syntax error in expanded macro: __draw_routes__:6: unexpected token: .

        def self.get__index.html(context, head_request)
```

**Comment by jackturnbull** [comment]
Turns out it was a doddle: https://github.com/spider-gazelle/action-controller/pull/10

**Comment by stakach** [comment]
Thanks for the pull and great catch!
Also when I changed how those routes are defined I made named routes optional.

```
  get "index.html", :index_html do
    render text: "<html></html>"
  end

  # can now be defined

  get "index.html" do
    render text: "<html></html>"
  end
```

A route name is auto-generated: `:get_index_html` in this case.
So you can do this if desired:

```
def show
  redirect_to Welcome.get_index_html
end
```
